"""
Critic Agent Module
Evaluates the generated reasoning against the biological evidence.
"""
import sys
import os
import json
from typing import Dict, Any
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from pydantic import BaseModel, Field

# Add project root to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.config import get_llm
from agents.state import AgentState

# Define the expected JSON output structure
class CriticResponse(BaseModel):
    status: str = Field(description="The evaluation result, either 'PASS' or 'REVISE'")
    feedback: str = Field(description="Specific feedback pointing out contradictions or hallucinations, or approval message")

def critic_node(state: AgentState) -> Dict[str, Any]:
    """
    LangGraph Node: Critic
    
    Acts as a strict bioinformatics reviewer.
    Checks if the draft reasoning matches the provided feature data.
    
    Args:
        state (AgentState): Current graph state.
        
    Returns:
        dict: Updates to the state (critique_passed, critique_feedback)
    """
    print("--- [Critic Agent] Reviewing draft... ---")
    
    # Setup LLM
    llm = get_llm(temperature=0.1) # Low temp for strict evaluation
    
    # Setup Parser
    parser = JsonOutputParser(pydantic_object=CriticResponse)
    
    # Prepare Prompt
    system_template = """You are a strict Bioinformatics Reviewer and Scientific Editor.
    Your task is to evaluate a connection prediction between a miRNA and a Disease.
    
    You have two inputs:
    1. GROUND TRUTH EVIDENCE (Feature Data): Numerical scores from various algorithms (RWR, Similarity, Graph).
    2. DRAFT REASONING: A qualitative description generated by another agent.
    
    CRITERIA FOR "REVISE":
    - Hallucination: The draft mentions numbers or scores that do not exist in the Evidence.
    - Contradiction: The draft claims "High probability" when RWR score is effectively zero, or vice versa.
    - Omission: The draft ignores strong signal provided in the Evidence.
    
    CRITERIA FOR "PASS":
    - The reasoning accurately reflects the numerical data.
    - It does not overstate the confidence if scores are low.
    - It correctly interprets the specific biological context provided.
    
    CRITICAL JSON FORMATTING:
    - Your output MUST be strictly valid JSON without markdown wrapping.
    - If you need to use quotes inside the "feedback" string, you MUST use single quotes (') or properly escape double quotes (\\"). Do NOT use unescaped double quotes inside your string values!

    Format your response as a JSON object with keys 'status' (PASS/REVISE) and 'feedback'.
    {format_instructions}
    """
    
    human_template = """
    Target Pair: {mirna_id} - {disease_id}
    
    === GROUND TRUTH EVIDENCE ===
    {feature_data}
    
    === DRAFT REASONING TO REVIEW ===
    {draft_reasoning}
    """
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_template),
        ("human", human_template)
    ])
    
    chain = prompt | llm | parser
    
    # Execute
    try:
        # Convert feature dict to string for prompt
        feature_str = json.dumps(state["feature_data"], indent=2)
        
        response = chain.invoke({
            "mirna_id": state["mirna_id"],
            "disease_id": state["disease_id"],
            "feature_data": feature_str,
            "draft_reasoning": state["draft_reasoning"],
            "format_instructions": parser.get_format_instructions()
        })
        
        status = response.get("status", "REVISE").upper()
        feedback = response.get("feedback", "No feedback provided.")
        
        passed = (status == "PASS")
        
        print(f"--- [Critic Agent] Decision: {status} ---")
        
        return {
            "critique_passed": passed,
            "critique_feedback": feedback
        }
        
    except Exception as e:
        print(f"Error in Critic Agent: {e}")
        # Fallback in case of parsing error: force revision or pass depending on risk policy
        return {
            "critique_passed": False,
            "critique_feedback": f"System Error during critique: {e}. Please regenerate."
        }
