"""
Definition of the Graph State for the Multi-Agent workflow.
This state is passed between nodes in the LangGraph execution loop.
"""
from typing import TypedDict, Dict, Optional

class AgentState(TypedDict):
    """
    Represents the shared state of the LangGraph workflow for miRNA-Disease prediction.
    Targeting a Critic-Refine loop architecture.
    """
    # Input identifiers
    mirna_id: str
    disease_id: str

    # Aggregated context
    feature_data: Dict  # Stores numerical/text features from RWR, Sim, Graph agents

    # Generation State
    draft_reasoning: Optional[str]  # The initial or revised reasoning generated by Fusion/Refiner
    
    # Critique State
    critique_feedback: Optional[str]  # Structured feedback provided by the Critic Agent
    critique_passed: bool  # Flag determining if the workflow should exit or refine
    
    # Loop Guard
    revision_count: int  # Counter to limit the number of refinement iterations
